# shellcheck shell=sh

post_install() {
    if command -v update-mime-database >/dev/null 2>&1; then
        update-mime-database /usr/share/mime >/dev/null 2>&1 || true
    fi
    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database -q /usr/share/applications >/dev/null 2>&1 || true
    fi
}

post_upgrade() {
    post_install "$@"
}

post_remove() {
    post_install "$@"
}
